package com.example.elderhelpprototypev01.ui.localization

data class AppStrings(
    val appSubtitle: String,
    val statusText: String,
    val listeningText: String,
    val tapToSpeak: String,
    val tapToStop: String,
    val micSubtitle: String,
    val exploreTasks: String,
    val seeAll: String,
    val doctorTitle: String,
    val doctorSubtitle: String,
    val doctorBtn: String,
    val billsTitle: String,
    val billsSubtitle: String,
    val billsBtn: String,
    val formsTitle: String,
    val formsSubtitle: String,
    val formsBtn: String,
    val helpTitle: String,
    val helpSubtitle: String,
    val helpBtn: String,
    val sosTitle: String,
    val sosSubtitle: String,
    val sosBtn: String,
    val navHome: String,
    val navVoice: String,
    val navTransactions: String,
    val navSettings: String,
    val welcomePill: String,
    val settingsTitle: String,
    val settingsSubtitle: String,
    val prefLanguageTitle: String,
    val emergencySos: String = "EMERGENCY SOS",
    val cancel: String = "Cancel",
    // Emergency Services
    val emergencyServicesTitle: String = "Emergency Services",
    val callEmergencyContact: String = "Call Emergency Contact",
    val findNearestPolice: String = "Find Nearest Police Station",
    val locationRequired: String = "Location access is required to find nearby police stations",
    val grantLocation: String = "Grant Location Access",
    val openingMaps: String = "Opening Google Maps…",
    val callingContact: String = "Calling emergency contact…",
    val close: String = "Close",
    // Redesigned Doctor Booking Flow & Compact Tasks
    val bookDoctor: String = "Book Doctor",
    val governmentForms: String = "Government Forms",
    val emergencyAssistance: String = "Emergency Assistance",
    val chooseSpecialty: String = "Choose Specialty",
    val chooseDoctor: String = "Choose Doctor",
    val appointmentDetails: String = "Appointment Details",
    val bookingConfirmed: String = "Booking Confirmed",
    val patientName: String = "Patient Name",
    val patientAge: String = "Age",
    val patientPhone: String = "Phone Number",
    val selectDate: String = "Select Date",
    val selectTime: String = "Select Time",
    val consultationMode: String = "Consultation Mode",
    val inPersonVisit: String = "In-Person Clinic Visit",
    val onlineConsultation: String = "Online Consultation",
    val confirmAndBook: String = "Confirm & Book Appointment",
    val done: String = "Done",
    val back: String = "Back",
    val relationship: String = "Relationship"
)

object Localization {
    fun getStrings(language: String): AppStrings = when {
        language.contains("Hindi") || language.contains("हिंदी") -> AppStrings(
            appSubtitle = "आपका डिजिटल साथी",
            statusText = "मैं आपकी मदद के लिए यहाँ हूँ।",
            listeningText = "ध्यान से सुन रहा हूँ...",
            tapToSpeak = "बोलने के लिए टैप करें",
            tapToStop = "रोकने के लिए टैप करें",
            micSubtitle = "ElderhelpV0.1 से पूछने के लिए नीला बटन दबाएं",
            exploreTasks = "त्वरित सेवाएँ",
            seeAll = "सभी देखें",
            doctorTitle = "डॉक्टर अपॉइंटमेंट",
            doctorSubtitle = "क्लिनिक विजिट बुक करें",
            doctorBtn = "बुक करें",
            billsTitle = "बिल भुगतान",
            billsSubtitle = "बिजली और पानी का बिल",
            billsBtn = "भुगतान करें",
            formsTitle = "सरकारी फॉर्म्स",
            formsSubtitle = "पेंशन और आईडी फॉर्म्स",
            formsBtn = "खोलें",
            helpTitle = "आपातकालीन सहायता",
            helpSubtitle = "तुरंत सहायता प्राप्त करें",
            helpBtn = "मदद लें",
            sosTitle = "SOS आपातकाल",
            sosSubtitle = "तत्काल आपातकालीन कॉल",
            sosBtn = "अभी कॉल करें",
            navHome = "होम",
            navVoice = "आवाज़",
            navTransactions = "लेन-देन",
            navSettings = "सेटिंग्स",
            welcomePill = "नमस्ते! 🙏 स्वागत है",
            settingsTitle = "सेटिंग्स",
            settingsSubtitle = "पसंद और आपातकालीन सेटअप",
            prefLanguageTitle = "पसंदीदा भाषा",
            emergencyServicesTitle = "आपातकालीन सेवाएँ",
            callEmergencyContact = "आपातकालीन संपर्क को कॉल करें",
            findNearestPolice = "निकटतम पुलिस स्टेशन खोजें",
            locationRequired = "निकटतम पुलिस स्टेशन खोजने के लिए स्थान एक्सेस आवश्यक है",
            grantLocation = "स्थान एक्सेस दें",
            openingMaps = "Google Maps खोल रहे हैं…",
            callingContact = "आपातकालीन संपर्क को कॉल कर रहे हैं…",
            close = "बंद करें",
            bookDoctor = "डॉक्टर बुक करें",
            governmentForms = "सरकारी फॉर्म",
            emergencyAssistance = "आपातकालीन सहायता",
            chooseSpecialty = "विशेषज्ञता चुनें",
            chooseDoctor = "डॉक्टर चुनें",
            appointmentDetails = "अपॉइंटमेंट विवरण",
            bookingConfirmed = "अपॉइंटमेंट कन्फर्म हो गया",
            patientName = "मरीज़ का नाम",
            patientAge = "उम्र",
            patientPhone = "फोन नंबर",
            selectDate = "तारीख चुनें",
            selectTime = "समय चुनें",
            consultationMode = "परामर्श का तरीका",
            inPersonVisit = "क्लिनिक विज़िट",
            onlineConsultation = "ऑनलाइन परामर्श",
            confirmAndBook = "कन्फर्म करें और बुक करें",
            done = "हो गया",
            back = "पीछे",
            relationship = "संबंध"
        )
        language.contains("Marathi") || language.contains("मराठी") -> AppStrings(
            appSubtitle = "तुमचा डिजिटल साथीदार",
            statusText = "मी तुमच्या मदतीसाठी येथे आहे.",
            listeningText = "लक्षपूर्वक ऐकत आहे...",
            tapToSpeak = "बोलण्यासाठी टॅप करा",
            tapToStop = "थांबवण्यासाठी टॅप करा",
            micSubtitle = "ElderhelpV0.1 ला विचारण्यासाठी निळा बटण दाबा",
            exploreTasks = "जलद सेवा",
            seeAll = "सर्व पहा",
            doctorTitle = "डॉक्टर अपॉइंटमेंट",
            doctorSubtitle = "क्लिनिक भेट बुक करा",
            doctorBtn = "बुक करा",
            billsTitle = "बिल भरणा",
            billsSubtitle = "वीज आणि पाणी बिल",
            billsBtn = "बिल भरा",
            formsTitle = "शासकीय फॉर्म",
            formsSubtitle = "पेन्शन आणि आयडी फॉर्म",
            formsBtn = "उघडा",
            helpTitle = "तातडीची मदत",
            helpSubtitle = "त्वरित मदत मिळवा",
            helpBtn = "मदत घ्या",
            sosTitle = "SOS आपत्कालीन",
            sosSubtitle = "तत्काळ आपत्कालीन कॉल",
            sosBtn = "आत्ता कॉल करा",
            navHome = "मुख्य",
            navVoice = "आवाज",
            navTransactions = "व्यवहार",
            navSettings = "सेटिंग्ज",
            welcomePill = "नमस्कार! 🙏 स्वागत आहे",
            settingsTitle = "सेटिंग्ज",
            settingsSubtitle = "पसंती आणि आपत्कालीन सेटअप",
            prefLanguageTitle = "पसंतीची भाषा",
            emergencyServicesTitle = "आपत्कालीन सेवा",
            callEmergencyContact = "आपत्कालीन संपर्काला कॉल करा",
            findNearestPolice = "जवळचे पोलिस स्टेशन शोधा",
            locationRequired = "जवळचे पोलिस स्टेशन शोधण्यासाठी स्थान एक्सेस आवश्यक आहे",
            grantLocation = "स्थान एक्सेस द्या",
            openingMaps = "Google Maps उघडत आहे…",
            callingContact = "आपत्कालीन संपर्काला कॉल करत आहे…",
            close = "बंद करा"
        )
        language.contains("Tamil") || language.contains("தமிழ்") -> AppStrings(
            appSubtitle = "உங்கள் டிஜிட்டல் தோழன்",
            statusText = "நான் உங்களுக்கு உதவ இங்கே இருக்கிறேன்.",
            listeningText = "கவனமாகக் கேட்கிறது...",
            tapToSpeak = "பேச தட்டவும்",
            tapToStop = "நிறுத்த தட்டவும்",
            micSubtitle = "ElderhelpV0.1 இடம் கேட்க நீல பொத்தானை அழுத்தவும்",
            exploreTasks = "விரைவான சேவைகள்",
            seeAll = "அனைத்தும் காண்க",
            doctorTitle = "மருத்துவர் சந்திப்பு",
            doctorSubtitle = "சந்திப்பை முன்பதிவு செய்ய",
            doctorBtn = "முன்பதிவு",
            billsTitle = "கட்டணம் செலுத்த",
            billsSubtitle = "மின்சாரம் மற்றும் குடிநீர்",
            billsBtn = "செலுத்து",
            formsTitle = "அரசு படிவங்கள்",
            formsSubtitle = "ஓய்வூதியம் மற்றும் சான்றிதழ்",
            formsBtn = "திறக்கவும்",
            helpTitle = "அவசர உதவி",
            helpSubtitle = "உடனடி உதவி பெற",
            helpBtn = "உதவி",
            sosTitle = "SOS அவசரநிலை",
            sosSubtitle = "உடனடி அவசர அழைப்பு",
            sosBtn = "இப்போது அழைக்கவும்",
            navHome = "முகப்பு",
            navVoice = "குரல்",
            navTransactions = "பரிவர்த்தனைகள்",
            navSettings = "அமைப்புகள்",
            welcomePill = "வணக்கம்! 🙏 நல்வரவு",
            settingsTitle = "அமைப்புகள்",
            settingsSubtitle = "விருப்பத்தேர்வுகள் & அவசரநிலை",
            prefLanguageTitle = "விருப்பமான மொழி",
            emergencyServicesTitle = "அவசர சேவைகள்",
            callEmergencyContact = "அவசர தொடர்பை அழைக்கவும்",
            findNearestPolice = "அருகிலுள்ள காவல் நிலையம் கண்டறியவும்",
            locationRequired = "அருகிலுள்ள காவல் நிலையத்தைக் கண்டறிய இருப்பிட அணுகல் தேவை",
            grantLocation = "இருப்பிட அணுகலை வழங்கவும்",
            openingMaps = "Google Maps திறக்கிறது…",
            callingContact = "அவசர தொடர்பை அழைக்கிறது…",
            close = "மூடு"
        )
        language.contains("Telugu") || language.contains("తెలుగు") -> AppStrings(
            appSubtitle = "మీ డిజిటల్ తోడు",
            statusText = "నేను మీకు సహాయం చేయడానికి ఇక్కడ ఉన్నాను.",
            listeningText = "శ్రద్ధగా వింటున్నాను...",
            tapToSpeak = "మాట్లాడటానికి నొక్కండి",
            tapToStop = "ఆపడానికి నొక్కండి",
            micSubtitle = "ElderhelpV0.1 ని అడగడానికి నీలిరంగు బటన్ నొక్కండి",
            exploreTasks = "వేగవంతమైన సేవలు",
            seeAll = "అన్నీ చూడండి",
            doctorTitle = "డాక్టర్ అపాయింట్‌మెంట్",
            doctorSubtitle = "క్లినిక్ విజిట్ బుక్ చేయండి",
            doctorBtn = "బుక్ చేయండి",
            billsTitle = "బిల్లు చెల్లింపు",
            billsSubtitle = "కరెంట్ మరియు మంచినీటి బిల్లు",
            billsBtn = "చెల్లించండి",
            formsTitle = "ప్రభుత్వ ఫారాలు",
            formsSubtitle = "పెన్షన్ మరియు ఐడీ ఫారాలు",
            formsBtn = "తెరిచి చూడండి",
            helpTitle = "అత్యవసర సహాయం",
            helpSubtitle = "తక్షణ సహాయం పొందండి",
            helpBtn = "సహాయం",
            sosTitle = "SOS అత్యవసర",
            sosSubtitle = "తక్షణ అత్యవసర కాల్",
            sosBtn = "ఇప్పుడు కాల్ చేయండి",
            navHome = "హోమ్",
            navVoice = "వాయిస్",
            navTransactions = "లావాదేవీలు",
            navSettings = "సెట్టింగ్స్",
            welcomePill = "నమస్కారం! 🙏 స్వాగతం",
            settingsTitle = "సెట్టింగ్స్",
            settingsSubtitle = "అభిరుచులు & అత్యవసర విభాగాలు",
            prefLanguageTitle = "ఎంచుకున్న భాష",
            emergencyServicesTitle = "అత్యవసర సేవలు",
            callEmergencyContact = "అత్యవసర సంప్రదింపును కాల్ చేయండి",
            findNearestPolice = "సమీపంలోని పోలీస్ స్టేషన్ కనుగొనండి",
            locationRequired = "సమీపంలోని పోలీస్ స్టేషన్ కనుగొనడానికి స్థాన యాక్సెస్ అవసరం",
            grantLocation = "స్థాన యాక్సెస్ ఇవ్వండి",
            openingMaps = "Google Maps తెరుస్తోంది…",
            callingContact = "అత్యవసర సంప్రదింపుకు కాల్ చేస్తోంది…",
            close = "మూసివేయండి"
        )
        language.contains("Bengali") || language.contains("বাংলা") -> AppStrings(
            appSubtitle = "আপনার ডিজিটাল সঙ্গী",
            statusText = "আমি আপনাকে সাহায্য করতে এখানে আছি।",
            listeningText = "মনোযোগ দিয়ে শুনছি...",
            tapToSpeak = "কথা বলতে ট্যাপ করুন",
            tapToStop = "থামাতে ট্যাপ করুন",
            micSubtitle = "ElderhelpV0.1 কে জিজ্ঞাসা করতে নীল বোতামটি চাপুন",
            exploreTasks = "দ্রুত পরিষেবা",
            seeAll = "সব দেখুন",
            doctorTitle = "ডাক্তারের অ্যাপয়েন্টমেন্ট",
            doctorSubtitle = "ক্লিনিক ভিজিট বুক করুন",
            doctorBtn = "বুক করুন",
            billsTitle = "বিল পরিশোধ",
            billsSubtitle = "বিদ্যুৎ ও জলের বিল",
            billsBtn = "পরিশোধ করুন",
            formsTitle = "সরকারি ফর্ম",
            formsSubtitle = "পেনশন ও আইডি ফর্ম",
            formsBtn = "খুলুন",
            helpTitle = "জরুরি সহায়তা",
            helpSubtitle = "তাত্ক্ষণিক সহায়তা পান",
            helpBtn = "সাহায্য নিন",
            sosTitle = "SOS জরুরি অবস্থা",
            sosSubtitle = "তাৎক্ষণিক জরুরি কল",
            sosBtn = "এখনই কল করুন",
            navHome = "হোম",
            navVoice = "ভয়েস",
            navTransactions = "লেনদেন",
            navSettings = "সেটিংস",
            welcomePill = "নমস্কার! 🙏 স্বাগতম",
            settingsTitle = "সেটিংস",
            settingsSubtitle = "পছন্দ এবং জরুরি সেটআপ",
            prefLanguageTitle = "পছন্দের ভাষা",
            emergencyServicesTitle = "জরুরি সেবা",
            callEmergencyContact = "জরুরি যোগাযোগে কল করুন",
            findNearestPolice = "নিকটতম থানা খুঁজুন",
            locationRequired = "নিকটতম থানা খুঁজতে অবস্থান অ্যাক্সেস প্রয়োজন",
            grantLocation = "অবস্থান অ্যাক্সেস দিন",
            openingMaps = "Google Maps খুলছে…",
            callingContact = "জরুরি যোগাযোগে কল করা হচ্ছে…",
            close = "বন্ধ করুন"
        )
        else -> AppStrings(
            appSubtitle = "Your digital companion",
            statusText = "I'm here to help.",
            listeningText = "Listening carefully...",
            tapToSpeak = "Tap to speak",
            tapToStop = "Tap to stop",
            micSubtitle = "Press the blue button to ask ElderhelpV0.1",
            exploreTasks = "Explore Quick Tasks",
            seeAll = "See all",
            doctorTitle = "Doctor Appointment",
            doctorSubtitle = "Book clinic visits",
            doctorBtn = "Book",
            billsTitle = "Pay Bills",
            billsSubtitle = "Electricity & water",
            billsBtn = "Pay",
            formsTitle = "Forms",
            formsSubtitle = "Pension & ID forms",
            formsBtn = "Open",
            helpTitle = "Help",
            helpSubtitle = "Get quick support",
            helpBtn = "Get Help",
            sosTitle = "SOS Emergency",
            sosSubtitle = "Instant emergency alert",
            sosBtn = "Call Now",
            navHome = "Home",
            navVoice = "Voice",
            navTransactions = "Transactions",
            navSettings = "Settings",
            welcomePill = "Namaste! 🙏 Welcome",
            settingsTitle = "Settings",
            settingsSubtitle = "Preferences & Emergency Setup",
            prefLanguageTitle = "Preferred Language"
        )
    }
}
